trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      python -m pip install --upgrade pip
      pip install -r environment.yml
    displayName: 'Install dependencies'

  - task: AzureCLI@2
    inputs:
      azureSubscription: '<Azure Service Connection>'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az extension add -n azure-cli-ml
        az ml workspace attach -g $(ResourceGroup) -w $(WorkspaceName)

  - script: python train.py
    displayName: 'Run Training Script'

  - script: python register_model.py
    displayName: 'Register Model'
